language: php
php:
  - "5.4"

env:
  global:
    - CORE_BRANCH=stable7

before_install:
- sudo apt-get update
- sudo pip install requests
- sudo apt-get install apache2 libapache2-mod-fastcgi
- bash travis-build/install_oc.sh $CORE_BRANCH
# enable php-fpm
- sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
- sudo a2enmod rewrite actions fastcgi alias
- echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
- ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
# configure apache virtual hosts
- sudo cp -f travis-build/travis-ci-apache /etc/apache2/sites-available/default
- sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
- sudo service apache2 restart

script:
  # execute unit tests
  - ./runtests.sh
